var namespaceFQLab =
[
    [ "PluginContracts", "namespaceFQLab_1_1PluginContracts.html", "namespaceFQLab_1_1PluginContracts" ],
    [ "AudioEngine", "classFQLab_1_1AudioEngine.html", "classFQLab_1_1AudioEngine" ],
    [ "AudioEngineFactory", "classFQLab_1_1AudioEngineFactory.html", "classFQLab_1_1AudioEngineFactory" ],
    [ "AudioStreamWrapper", "classFQLab_1_1AudioStreamWrapper.html", "classFQLab_1_1AudioStreamWrapper" ],
    [ "ControlPanelView", "classFQLab_1_1ControlPanelView.html", "classFQLab_1_1ControlPanelView" ],
    [ "EqColumn", "classFQLab_1_1EqColumn.html", "classFQLab_1_1EqColumn" ],
    [ "EqSelectorView", "classFQLab_1_1EqSelectorView.html", "classFQLab_1_1EqSelectorView" ],
    [ "EqSettings", "structFQLab_1_1EqSettings.html", "structFQLab_1_1EqSettings" ],
    [ "FreqAxisView", "classFQLab_1_1FreqAxisView.html", "classFQLab_1_1FreqAxisView" ],
    [ "FreqGraphView", "classFQLab_1_1FreqGraphView.html", "classFQLab_1_1FreqGraphView" ],
    [ "FreqSpectrumView", "classFQLab_1_1FreqSpectrumView.html", "classFQLab_1_1FreqSpectrumView" ],
    [ "FreqViewDataProcessor", "classFQLab_1_1FreqViewDataProcessor.html", "classFQLab_1_1FreqViewDataProcessor" ],
    [ "IAudioEngineFactory", "interfaceFQLab_1_1IAudioEngineFactory.html", "interfaceFQLab_1_1IAudioEngineFactory" ],
    [ "IAudioPlayer", "interfaceFQLab_1_1IAudioPlayer.html", "interfaceFQLab_1_1IAudioPlayer" ],
    [ "IAudioReader", "interfaceFQLab_1_1IAudioReader.html", "interfaceFQLab_1_1IAudioReader" ],
    [ "IAudioStream", "interfaceFQLab_1_1IAudioStream.html", "interfaceFQLab_1_1IAudioStream" ],
    [ "IFftProcessor", "interfaceFQLab_1_1IFftProcessor.html", "interfaceFQLab_1_1IFftProcessor" ],
    [ "IFreqDataReceiver", "interfaceFQLab_1_1IFreqDataReceiver.html", "interfaceFQLab_1_1IFreqDataReceiver" ],
    [ "InputHandler", "classFQLab_1_1InputHandler.html", "classFQLab_1_1InputHandler" ],
    [ "InputSelectWindow", "classFQLab_1_1InputSelectWindow.html", "classFQLab_1_1InputSelectWindow" ],
    [ "Logger", "classFQLab_1_1Logger.html", "classFQLab_1_1Logger" ],
    [ "LoggerAudioPlayer", "classFQLab_1_1LoggerAudioPlayer.html", "classFQLab_1_1LoggerAudioPlayer" ],
    [ "MathNetFftProcessor", "classFQLab_1_1MathNetFftProcessor.html", "classFQLab_1_1MathNetFftProcessor" ],
    [ "NAudioBufferedProvider", "classFQLab_1_1NAudioBufferedProvider.html", "classFQLab_1_1NAudioBufferedProvider" ],
    [ "NAudioPlayer", "classFQLab_1_1NAudioPlayer.html", "classFQLab_1_1NAudioPlayer" ],
    [ "NAudioReaderAdapter", "classFQLab_1_1NAudioReaderAdapter.html", "classFQLab_1_1NAudioReaderAdapter" ],
    [ "PlayingWindow", "classFQLab_1_1PlayingWindow.html", "classFQLab_1_1PlayingWindow" ],
    [ "Plugin", "classFQLab_1_1Plugin.html", "classFQLab_1_1Plugin" ],
    [ "PluginInstance", "classFQLab_1_1PluginInstance.html", "classFQLab_1_1PluginInstance" ],
    [ "PluginListView", "classFQLab_1_1PluginListView.html", "classFQLab_1_1PluginListView" ],
    [ "PluginLoader", "classFQLab_1_1PluginLoader.html", "classFQLab_1_1PluginLoader" ],
    [ "Program", "classFQLab_1_1Program.html", "classFQLab_1_1Program" ],
    [ "SimpleFileBrowser", "classFQLab_1_1SimpleFileBrowser.html", "classFQLab_1_1SimpleFileBrowser" ],
    [ "SineWaveStream", "classFQLab_1_1SineWaveStream.html", "classFQLab_1_1SineWaveStream" ],
    [ "UIController", "classFQLab_1_1UIController.html", "classFQLab_1_1UIController" ],
    [ "EqRanges", "namespaceFQLab.html#a7a636950fe6b33f651eecb8411064a48", [
      [ "Lows", "namespaceFQLab.html#a7a636950fe6b33f651eecb8411064a48a13a10e417d759d9e4990a50baff72257", null ],
      [ "Mids", "namespaceFQLab.html#a7a636950fe6b33f651eecb8411064a48a4df48b09ff1e38c8b75d8323a6ac3af4", null ],
      [ "Highs", "namespaceFQLab.html#a7a636950fe6b33f651eecb8411064a48a14411703b67ccb38a5a53f50c1852e1d", null ]
    ] ],
    [ "AudioEngineFactoryResult", "namespaceFQLab.html#a1b2595c4a53c99235ad5632bbe556b69", null ],
    [ "AudioFrame", "namespaceFQLab.html#a7b2f30b69db5722f8e5226c476f40633", null ],
    [ "FreqViewData", "namespaceFQLab.html#a2e96c171ac1206d46d6217888d9c8576", null ]
];